services:
  chromadb:
    image: chromadb/chroma:latest
    volumes:
      - ./chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - "8750:8000"
    networks:
      - net
  chroma-admin:
    image: wonderooo/chromadb-admin:v0.1
    ports:
      - "3750:3000"
    networks:
      - net

networks:
  net:
    driver: bridge